# Generated by Django 4.2.2 on 2023-06-27 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 4, 38, 41, 831328, tzinfo=datetime.timezone.utc))),
                ('likes', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField()),
                ('views_people', models.CharField(max_length=100)),
            ],
        ),
    ]
