# Generated by Django 4.2.2 on 2023-06-27 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 4, 39, 28, 582946, tzinfo=datetime.timezone.utc)),
        ),
    ]
