# Generated by Django 4.2.2 on 2023-06-27 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_alter_story_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 5, 44, 12, 322706, tzinfo=datetime.timezone.utc)),
        ),
    ]
