# Generated by Django 4.2.2 on 2023-06-27 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 4, 39, 28, 585104, tzinfo=datetime.timezone.utc)),
        ),
    ]
