# Generated by Django 4.2.2 on 2023-06-27 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 5, 29, 51, 575920, tzinfo=datetime.timezone.utc)),
        ),
    ]
