# Generated by Django 4.2.2 on 2023-06-28 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_board_review_user_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 28, 5, 14, 5, 691386, tzinfo=datetime.timezone.utc)),
        ),
    ]
